// Movies dataset — real titles, no external images. Posters are typographic.
// Each movie has a "seed" hue used to tint its typographic poster so shelves feel varied.

const MOVIES = [
  // --- core 3 (used in "3 items" state) ---
  { id:'lalaland', ru:'Ла-Ла Ленд', en:'La La Land', year:2016, dir:'Damien Chazelle', runtime:128,
    genre:['musical','romance'], hue:28, type:'warm',
    source:'telegram', sourceNote:{ ru:'Из канала «Киноварь»', en:'From «Kinovar» channel' },
    why:{ ru:'«Подняло настроение на целую неделю»', en:'"Lifted my mood for a week"' },
    myRating:9, publicRating:8.0, watched:false, savedDaysAgo:3 },
  { id:'past-lives', ru:'Прошлые жизни', en:'Past Lives', year:2023, dir:'Celine Song', runtime:105,
    genre:['drama','romance'], hue:340, type:'cool',
    source:'friends', sourceNote:{ ru:'Посоветовала Аня', en:'Anya recommended' },
    why:{ ru:'«Тихий, про "что, если…"»', en:'"A quiet what-if film"' },
    myRating:8, publicRating:7.8, watched:false, savedDaysAgo:8 },
  { id:'perfect-days', ru:'Идеальные дни', en:'Perfect Days', year:2023, dir:'Wim Wenders', runtime:124,
    genre:['drama'], hue:90, type:'warm',
    source:'instagram', sourceNote:{ ru:'Reel от @vkino', en:'Reel from @vkino' },
    why:{ ru:'«Медитативный. Токио и Lou Reed»', en:'"Meditative. Tokyo and Lou Reed"' },
    myRating:9, publicRating:7.9, watched:false, savedDaysAgo:12 },

  // --- extras for 20+ state ---
  { id:'paddington-2', ru:'Приключения Паддингтона 2', en:'Paddington 2', year:2017, dir:'Paul King', runtime:103,
    genre:['comedy','family'], hue:18, type:'warm',
    source:'friends', sourceNote:{ ru:'Настя: «под пиццу»', en:'Nastya: "for pizza night"' },
    why:{ ru:'«Самый милый фильм в мире»', en:'"The coziest film ever"' },
    myRating:9, publicRating:8.2, watched:true, savedDaysAgo:45 },
  { id:'drive', ru:'Драйв', en:'Drive', year:2011, dir:'Nicolas Winding Refn', runtime:100,
    genre:['thriller','drama'], hue:320, type:'cool',
    source:'telegram', sourceNote:{ ru:'Подборка «10 ночных»', en:'"10 night films" list' },
    why:{ ru:'«Розовый шрифт, Гослинг, молчание»', en:'"Pink typeface, Gosling, silence"' },
    myRating:9, publicRating:7.8, watched:true, savedDaysAgo:60 },
  { id:'grand-budapest', ru:'Отель «Гранд Будапешт»', en:'The Grand Budapest Hotel', year:2014, dir:'Wes Anderson', runtime:99,
    genre:['comedy','drama'], hue:350, type:'warm',
    source:'instagram', sourceNote:{ ru:'Reel @thatfilmgirl', en:'Reel @thatfilmgirl' },
    why:{ ru:'«Розовый торт и симметрия»', en:'"Pink cake & symmetry"' },
    myRating:10, publicRating:8.1, watched:true, savedDaysAgo:70 },
  { id:'portrait', ru:'Портрет девушки в огне', en:'Portrait of a Lady on Fire', year:2019, dir:'Céline Sciamma', runtime:122,
    genre:['drama','romance'], hue:12, type:'warm',
    source:'friends', sourceNote:{ ru:'Лена: «на выходных»', en:'Lena: "for the weekend"' },
    why:{ ru:'«Огонь, взгляд, Вивальди»', en:'"Fire, a gaze, Vivaldi"' },
    myRating:10, publicRating:8.1, watched:false, savedDaysAgo:40 },
  { id:'parasite', ru:'Паразиты', en:'Parasite', year:2019, dir:'Bong Joon-ho', runtime:132,
    genre:['thriller','drama'], hue:60, type:'warm',
    source:'telegram', sourceNote:{ ru:'Рецензия в «Сеансе»', en:'Review in Seance' },
    why:{ ru:'«Начинается как комедия»', en:'"Starts as a comedy"' },
    myRating:9, publicRating:8.5, watched:true, savedDaysAgo:120 },
  { id:'zone', ru:'Зона интересов', en:'The Zone of Interest', year:2023, dir:'Jonathan Glazer', runtime:106,
    genre:['drama'], hue:200, type:'cool',
    source:'telegram', sourceNote:{ ru:'«Искусство кино»', en:'«Iskusstvo Kino»' },
    why:{ ru:'«Смотреть внимательно, со звуком»', en:'"Watch carefully, with sound"' },
    myRating:8, publicRating:7.4, watched:false, savedDaysAgo:18 },
  { id:'aftersun', ru:'Солнце моё', en:'Aftersun', year:2022, dir:'Charlotte Wells', runtime:101,
    genre:['drama'], hue:38, type:'warm',
    source:'instagram', sourceNote:{ ru:'Reel @kinopoisk_notes', en:'Reel @kinopoisk_notes' },
    why:{ ru:'«Отец и дочь, плёнка, Турция»', en:'"Dad and daughter, film, Turkey"' },
    myRating:9, publicRating:7.6, watched:false, savedDaysAgo:22 },
  { id:'anatomy', ru:'Анатомия падения', en:'Anatomy of a Fall', year:2023, dir:'Justine Triet', runtime:151,
    genre:['drama','thriller'], hue:220, type:'cool',
    source:'friends', sourceNote:{ ru:'Максим прислал', en:'Maxim sent' },
    why:{ ru:'«Лучший суд на экране»', en:'"Best courtroom in years"' },
    myRating:9, publicRating:7.7, watched:true, savedDaysAgo:90 },
  { id:'moonlight', ru:'Лунный свет', en:'Moonlight', year:2016, dir:'Barry Jenkins', runtime:111,
    genre:['drama'], hue:260, type:'cool',
    source:'telegram', sourceNote:{ ru:'«Ночной киноклуб»', en:'"Night film club"' },
    why:{ ru:'«Синий, неон, океан»', en:'"Blue, neon, ocean"' },
    myRating:10, publicRating:7.4, watched:true, savedDaysAgo:150 },
  { id:'lobster', ru:'Лобстер', en:'The Lobster', year:2015, dir:'Yorgos Lanthimos', runtime:119,
    genre:['comedy','drama'], hue:150, type:'cool',
    source:'telegram', sourceNote:{ ru:'Канал «Странное кино»', en:'«Strange Cinema» channel' },
    why:{ ru:'«Если не влюбишься — в зверя»', en:'"Fall in love or become an animal"' },
    myRating:7, publicRating:7.1, watched:false, savedDaysAgo:200 },
  { id:'chef', ru:'Повар на колёсах', en:'Chef', year:2014, dir:'Jon Favreau', runtime:114,
    genre:['comedy'], hue:14, type:'warm',
    source:'instagram', sourceNote:{ ru:'Reel от @eatandwatch', en:'Reel from @eatandwatch' },
    why:{ ru:'«Не смотреть голодным»', en:'"Don\u2019t watch hungry"' },
    myRating:8, publicRating:7.3, watched:true, savedDaysAgo:80 },
  { id:'look-back', ru:'Оглянись', en:'Look Back', year:2024, dir:'Kiyotaka Oshiyama', runtime:58,
    genre:['animation','drama'], hue:200, type:'cool',
    source:'telegram', sourceNote:{ ru:'«Анимация на пятницу»', en:'«Friday Animation»' },
    why:{ ru:'«58 минут, обязательно»', en:'"58 minutes, must-watch"' },
    myRating:10, publicRating:8.5, watched:false, savedDaysAgo:6 },
  { id:'flow', ru:'Поток', en:'Flow', year:2024, dir:'Gints Zilbalodis', runtime:85,
    genre:['animation'], hue:170, type:'cool',
    source:'friends', sourceNote:{ ru:'Ира прислала', en:'Ira sent' },
    why:{ ru:'«Без слов. Кот и потоп»', en:'"Wordless. A cat and a flood"' },
    myRating:9, publicRating:8.3, watched:false, savedDaysAgo:4 },
  { id:'florida', ru:'Проект «Флорида»', en:'The Florida Project', year:2017, dir:'Sean Baker', runtime:111,
    genre:['drama'], hue:300, type:'warm',
    source:'instagram', sourceNote:{ ru:'Reel @whatiwatched', en:'Reel @whatiwatched' },
    why:{ ru:'«Сиреневый мотель, детство»', en:'"Lilac motel, childhood"' },
    myRating:9, publicRating:7.6, watched:true, savedDaysAgo:110 },
  { id:'handmaiden', ru:'Служанка', en:'The Handmaiden', year:2016, dir:'Park Chan-wook', runtime:145,
    genre:['thriller','drama'], hue:280, type:'cool',
    source:'telegram', sourceNote:{ ru:'«Корейская волна»', en:'«Korean Wave»' },
    why:{ ru:'«Три акта, три сюрприза»', en:'"Three acts, three surprises"' },
    myRating:10, publicRating:8.1, watched:true, savedDaysAgo:220 },
  { id:'frances-ha', ru:'Фрэнсис Ха', en:'Frances Ha', year:2012, dir:'Noah Baumbach', runtime:86,
    genre:['comedy','drama'], hue:0, type:'cool',
    source:'friends', sourceNote:{ ru:'Катя: «в твоём духе»', en:'Katya: "your vibe"' },
    why:{ ru:'«Чёрно-белый Нью-Йорк, Гервиг»', en:'"B&W NYC, Gerwig"' },
    myRating:9, publicRating:7.4, watched:false, savedDaysAgo:260 },
  { id:'challengers', ru:'Претенденты', en:'Challengers', year:2024, dir:'Luca Guadagnino', runtime:131,
    genre:['drama','romance'], hue:50, type:'warm',
    source:'instagram', sourceNote:{ ru:'Reel @tennisclub', en:'Reel @tennisclub' },
    why:{ ru:'«Теннис, Трент Резнор, пот»', en:'"Tennis, Trent Reznor, sweat"' },
    myRating:8, publicRating:7.1, watched:true, savedDaysAgo:30 },
  { id:'dune2', ru:'Дюна: Часть 2', en:'Dune: Part Two', year:2024, dir:'Denis Villeneuve', runtime:166,
    genre:['scifi'], hue:30, type:'warm',
    source:'telegram', sourceNote:{ ru:'«Большой экран»', en:'"Big screen" channel' },
    why:{ ru:'«Для звука»', en:'"For the sound"' },
    myRating:9, publicRating:8.5, watched:true, savedDaysAgo:50 },
  { id:'poor-things', ru:'Бедные-несчастные', en:'Poor Things', year:2023, dir:'Yorgos Lanthimos', runtime:141,
    genre:['comedy','scifi'], hue:310, type:'warm',
    source:'telegram', sourceNote:{ ru:'«Лантимос всё»', en:'«Lanthimos everything»' },
    why:{ ru:'«Странно и красиво»', en:'"Weird and beautiful"' },
    myRating:8, publicRating:7.8, watched:false, savedDaysAgo:14 },
  { id:'holdovers', ru:'Оставленные', en:'The Holdovers', year:2023, dir:'Alexander Payne', runtime:133,
    genre:['drama','comedy'], hue:40, type:'warm',
    source:'friends', sourceNote:{ ru:'Дима: «на праздники»', en:'Dima: "for the holidays"' },
    why:{ ru:'«Тёплое, рождественское»', en:'"Warm, Christmas-y"' },
    myRating:8, publicRating:7.9, watched:true, savedDaysAgo:170 },
  { id:'anora', ru:'Анора', en:'Anora', year:2024, dir:'Sean Baker', runtime:139,
    genre:['comedy','drama'], hue:355, type:'warm',
    source:'instagram', sourceNote:{ ru:'Reel @nyffnotes', en:'Reel @nyffnotes' },
    why:{ ru:'«Каннский хит, Брайтон-Бич»', en:'"Cannes hit, Brighton Beach"' },
    myRating:9, publicRating:7.6, watched:false, savedDaysAgo:2 },
];

// Copy dictionary RU/EN
const T = {
  appName:    { ru:'Ленточка',                       en:'Lentochka' },
  tagline:    { ru:'кино, которое ты отложил',       en:'the films you\u2019ve been saving' },
  addMovie:   { ru:'+ Добавить фильм',               en:'+ Add a film' },
  mood:       { ru:'Настроение',                     en:'Mood' },
  moodPh:     { ru:'лёгкое, ламповое, под пиццу…',   en:'light, cozy, pizza-night\u2026' },
  pick:       { ru:'Подобрать',                      en:'Pick one' },
  quickAdd:   { ru:'Быстро сохранить',                en:'Quick save' },
  quickAddPh: { ru:'вставь ссылку из соцсети…',      en:'paste a link from social\u2026' },
  save:       { ru:'Сохранить',                      en:'Save' },
  toWatch:    { ru:'Хочу посмотреть',                en:'To watch' },
  watched:    { ru:'Уже смотрел',                    en:'Watched' },
  friendMode: { ru:'Показать другу',                 en:'Share with a friend' },

  // shelf titles
  shelfToday: { ru:'Скорее всего сегодня',            en:'Probably tonight' },
  shelfRecent:{ ru:'Недавно добавленные',             en:'Recently added' },
  shelfWait:  { ru:'Давно откладываешь',              en:'Been waiting a while' },
  shelfShort: { ru:'До 90 минут',                     en:'Under 90 min' },
  shelfDrama: { ru:'Драмы',                           en:'Drama' },
  shelfComedy:{ ru:'Комедии',                         en:'Comedy' },
  shelfAnim:  { ru:'Анимация',                        en:'Animation' },
  shelfThr:   { ru:'Триллеры',                        en:'Thrillers' },

  emptyTitle: { ru:'Пока пусто — и это нормально',
                en:'Empty for now — that\u2019s fine' },
  emptySub:   { ru:'Увидел рекомендацию в ленте? Вставь ссылку — и фильм окажется здесь за 10 секунд. Вот как это выглядит:',
                en:'Saw a recommendation in your feed? Paste the link — a film lands here in 10 seconds. Here\u2019s what it looks like:' },

  min:        { ru:'мин',                              en:'min' },
  myScore:    { ru:'моё',                              en:'mine' },
  kp:         { ru:'КП',                               en:'IMDb' },
  because:    { ru:'Почему',                           en:'Why' },
  saved:      { ru:'сохранено',                        en:'saved' },
  daysAgo:    { ru:(n)=> n===1?'день назад':(n<5?'дня назад':'дней назад'),
                en:(n)=> n===1?'day ago':'days ago' },
  source_telegram:  { ru:'Из Telegram',   en:'From Telegram' },
  source_instagram: { ru:'Из Instagram',  en:'From Instagram' },
  source_friends:   { ru:'От друзей',     en:'From friends' },

  moodChips: {
    ru:['поплакать','классика','с друзьями','романтичный вечер','коротко, до 90 мин','что-то странное'],
    en:['a good cry','classic','with friends','romantic night','under 90 min','something weird'],
  },

  // pick-one result fake reasoning
  pickHeader:  { ru:'Твой выбор на вечер',   en:'Your pick for tonight' },
  pickBecause: { ru:'Почему именно этот',     en:'Why this one' },
  pickAgain:   { ru:'Ещё вариант',            en:'Try again' },
  pickClose:   { ru:'Закрыть',                en:'Close' },

  // quick-add preview
  quickParsed:   { ru:'Нашли по ссылке', en:'Parsed from link' },
  quickSource:   { ru:'Источник',        en:'Source' },
  quickKeep:     { ru:'Сохранить в «Хочу посмотреть»', en:'Save to "To watch"' },
  quickEdit:     { ru:'Изменить',        en:'Edit' },

  // tweaks panel
  tweaksLang:   { ru:'Язык',              en:'Language' },
  tweaksTheme:  { ru:'Тема',              en:'Theme' },
  tweaksState:  { ru:'Данные',            en:'Data' },
  tweaksDir:    { ru:'Направление',       en:'Direction' },
  tweaksFrame:  { ru:'Экран',             en:'Frame' },
  stateEmpty:   { ru:'Пусто',             en:'Empty' },
  state3:       { ru:'3 фильма',          en:'3 films' },
  state20:      { ru:'20+ фильмов',       en:'20+ films' },
  dirA:         { ru:'A · Заметки',       en:'A · Notes' },
  dirB:         { ru:'B · Лента',         en:'B · Rails' },
  frameMobile:  { ru:'Мобильный',         en:'Mobile' },
  frameDesktop: { ru:'Десктоп',           en:'Desktop' },
  themeLight:   { ru:'Светлая',           en:'Light' },
  themeDark:    { ru:'Тёмная',            en:'Dark' },

  // friend view header
  watchedSub:   { ru:'моя полка, можно показать',  en:'my shelf, hand over the phone' },
};

// Shelves (built from movies)
function buildShelves(movies, lang) {
  const byGenre = g => movies.filter(m => !m.watched && m.genre.includes(g));
  return [
    { id:'today',  title: T.shelfToday[lang],  items: movies.filter(m=>!m.watched).slice(0,8), tone:'hero' },
    { id:'recent', title: T.shelfRecent[lang], items: [...movies].filter(m=>!m.watched).sort((a,b)=>a.savedDaysAgo-b.savedDaysAgo).slice(0,10) },
    { id:'drama',  title: T.shelfDrama[lang],  items: byGenre('drama') },
    { id:'comedy', title: T.shelfComedy[lang], items: byGenre('comedy') },
    { id:'anim',   title: T.shelfAnim[lang],   items: byGenre('animation') },
    { id:'short',  title: T.shelfShort[lang],  items: movies.filter(m=>!m.watched && m.runtime<=100) },
    { id:'wait',   title: T.shelfWait[lang],   items: movies.filter(m=>!m.watched && m.savedDaysAgo>=30) },
  ].filter(s => s.items.length>=2);
}

Object.assign(window, { MOVIES, T, buildShelves });
