from backend.models.movie import (
    Movie,
    MovieBase,
    MovieCreate,
    MovieUpdate,
    RecommendationRequest,
    RecommendationResponse,
    OMDBSearchResult,
    MoviePreview,
    BulkImportItem,
    BulkImportRequest,
    Provider,
    WatchAvailability,
)
from backend.models.book import (
    Book,
    BookBase,
    BookCreate,
    BookUpdate,
    BookSearchResult,
    BookPreview,
    BookRecommendationRequest,
    BookRecommendationResponse,
    BookBulkImportItem,
    BookBulkImportRequest,
)
from backend.models.instagram import InstagramImportRequest
from backend.models.telegram import TelegramImportRequest
from backend.models.share import SharedListCreateRequest, SharedListResponse
from backend.models.user import (
    User,
    UserCreate,
    UserLogin,
    GoogleLogin,
    TelegramWebAppLogin,
    TelegramWidgetLogin,
    AuthResponse,
    UserSettings,
    UserSettingsUpdate,
)
from backend.models.event import EventIn, EventBatch, ALLOWED_EVENTS

__all__ = [
    "Movie",
    "MovieBase",
    "MovieCreate",
    "MovieUpdate",
    "Book",
    "BookBase",
    "BookCreate",
    "BookUpdate",
    "BookSearchResult",
    "BookPreview",
    "BookRecommendationRequest",
    "BookRecommendationResponse",
    "BookBulkImportItem",
    "BookBulkImportRequest",
    "RecommendationRequest",
    "RecommendationResponse",
    "OMDBSearchResult",
    "MoviePreview",
    "BulkImportItem",
    "BulkImportRequest",
    "Provider",
    "WatchAvailability",
    "InstagramImportRequest",
    "TelegramImportRequest",
    "SharedListCreateRequest",
    "SharedListResponse",
    "User",
    "UserCreate",
    "UserLogin",
    "GoogleLogin",
    "TelegramWebAppLogin",
    "TelegramWidgetLogin",
    "AuthResponse",
    "UserSettings",
    "UserSettingsUpdate",
    "EventIn",
    "EventBatch",
    "ALLOWED_EVENTS",
]
